services:
  - type: web
    name: rag-pdf-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --app-dir backend --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: LLM_BASE_URL
        value: https://api-inference.huggingface.co
      - key: LLM_MODEL
        value: Qwen/Qwen2.5-72B-Instruct
      - key: EMBEDDING_MODEL
        value: futur/Qwen3-Embedding-0.6B-model2vec-onnx
      - key: TOP_K
        value: "4"
      - key: LLM_API_KEY
        sync: false
